services:
  mongo:
    image: mongo:8.0
    container_name: portfolio_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/
      
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    command: sh -c "node seedDatas.js && npm run start"
  

  frontend:
    build: ./frontend  # chemin vers ton projet Vite
    volumes:
      - ./frontend:/app
      - /app/node_modules  # pour éviter d'écraser node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # pour hot-reload sous Docker
    command: npm run dev


volumes:
  mongo-data:
